[tox]
skipsdist = True
envlist = lint_all, testenv

[testenv]
passenv =
    # snowflake env vars
    SNOWFLAKE_USER
    SNOWFLAKE_WAREHOUSE
    SNOWFLAKE_ROLE
    SNOWFLAKE_DATABASE
    SNOWFLAKE_SCHEMA
    SNOWFLAKE_ACCOUNT
    DBT_ENV_SECRET_SNOWFLAKE_PASS

# Snowflake integration tests for centralized dbt testing
# run dbt commands directly, assumes dbt is already installed in environment
[testenv:dbt_integration_snowflake]
changedir = integration_tests
allowlist_externals = 
    dbt
    sleep
skip_install = true
commands =
    dbt deps
    dbt run-operation prep_structure
    dbt run --full-refresh
    dbt test
    dbt run-operation insert_data
    sleep 120
    dbt test
    dbt run-operation cleanup
